version: "2"
services:
  myapp:
    build: ./
    network_mode: host
    environment:
      ENV_PROD: 'true'
    command: ["gunicorn","--config", "file:gunicorn.conf.py" "--bind=0.0.0.0:5001", "mysite.wsgi:application"]